### ISSUE TITLE
[Feature]: Magic Link more login support: Google Oauth and SMS

### ISSUE THREAD

**Issue by jadbox** [blocknative/web3-onboard#1142]
### Is your request related to a problem?

We would like users to be able to login with social logins like Google OAuth or using Magic's SMS validation.

### Feature Description

Google OAuth docs:
https://magic.link/docs/login-methods/social-logins/integration/social-providers/google

SMS login docs:
https://magic.link/docs/login-methods/sms/integration/web

### Alternative Solutions

There is a fully prebuilt form option here, but it looks like the existing plugin would need to be refactored for it:
https://magic.link/docs/login-form

### Anything else?

none

**Comment by taylorjdawson** [comment]
Hey @jadbox! Would [this](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/magic/README.md) perhaps be what you're looking for?

**Comment by aaronbarnardsound** [comment]
@jadbox Yes our initial Magic integration was limited to just email login to start as it wasn't simple to support their other methods at the time. @Adamj1232 could take another look at this to see if there have been further developments on the magic SDK side, or if we can add to our custom UI.

**Comment by Adamj1232** [comment]
@jadbox we will look into this further. Currently the login form provided by Magic is only for no-code applications and has proven very challenging to be used in a library project as URL redirects are required by the low/no-code login form.
We opened a feature request with Magic a few months back that you can see [here](https://github.com/magiclabs/magic-js/issues/281). If you could comment on this we may get some traction. Otherwise we will need to write our own which is fine but it would be nice to have all available login options through the form as defined by the DApp users API key. If we don't hear from them shortly the approach will likely be to add a to the backlog and work it when the ticket makes its way to the top.

**Comment by Adamj1232** [comment]
We are currently working with the Magic team to land on a solution that can support all login features with Magic Link through their API

**Comment by Adamj1232** [comment]
@jadbox checking back in here. Response has been slow from the Magic team on making the login for available to SDK users. If you would like to create a PR to support this we are very open to it! Otherwise we will await Magic teams updates but there is currently no ETA

**Comment by ejc8** [comment]
Closing this for now but it is on our future/parking lot list
