### ISSUE TITLE
[Bug]: Metamask doesn't connect after installing web3 browser plugin from Avalanche named Core

### ISSUE THREAD

**Issue by matsveenman** [blocknative/web3-onboard#1159]
### Current Behavior

After installing the new web3 browser plugin from Avalanche named Core nothing happens when I try to connect Metamask via a Blocknative implemented website like Zapper.fi. After removing Core everything works fine. 

Core web3 plugin you can install from here https://chrome.google.com/webstore/detail/core/agoakfejjabomempkjlepdflaleeobhb)

### Expected Behavior

Regardless of whether Core browser plugin is installed, Metamask should connect after selecting Metamask in the block native wallet overview.

### Steps To Reproduce

1. Install Metamask browser plugin
2. Install Core https://chrome.google.com/webstore/detail/core/agoakfejjabomempkjlepdflaleeobhb/related
3. Visit Zapper.fi try to connect Metamask

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.5.0

### What browsers are you seeing the problem on?

Chrome

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by itsmnthn** [comment]
I have the same issue but after digging in I guess I found that core wallet exposes the wallet at `window.ethereum` which is also done by MetaMask and hence the Core wallet replaces the MetaMasks instance and we cannot access the MetaMask if we have Core wallet install. To do that you need to create new profile on your browser and install only one on one profile.

**Comment by Adamj1232** [comment]
@matsveenman even with native Web3-onboard support users will run into challenges viewing/using Core and MetaMask wallet at the same time because as @itsmnthn said above(and the[ officially noted work around](https://support.avax.network/en/articles/6333009-how-can-i-use-core-and-metamask-at-the-same-time)) the Core wallet overrides the `window.ethereum` space/object that is used by MetaMask, Coinbase, etc

**Comment by Adamj1232** [comment]
@itsmnthn we have reached out to AvaLabs to get the issues with the wallet provider resolved and will provide native support for Core wallet as soon as they have a fix in place

**Comment by Adamj1232** [comment]
We will close this issue for now since it is not an issue that can be addressed by Web3-Onboard currently but have surfaced this with AvaLabs. A workaround is noted in the official documentation [here](https://support.avax.network/en/articles/6333009-how-can-i-use-core-and-metamask-at-the-same-time) but it is up to the client to perform this workaround.
