### ISSUE TITLE
[Bug]: `otherProviderFlagsExist` function filters other wallet that is injected to the same namespace

### ISSUE THREAD

**Issue by slotZero01** [blocknative/web3-onboard#1534]
### Current Behavior

For example, when we have both metamask and exodus wallet active, the current behaviour is only exodus wallet is shown up and metamask is being filtered out due to both wallets injecting to the same namespace of `winow.ethereum`.

```
function otherProviderFlagsExist(identity: string, provider: any): boolean {
  const otherProviderFlags = Object.values(ProviderIdentityFlag).filter(
    id => id !== identity && id !== ProviderIdentityFlag.Detected
  )
  return otherProviderFlags.some(id => !!provider[id])
}
```

when metamask wallet is called, the function check if no other wallet injects to the same namespacewallets

### Expected Behavior

both wallets should appear

### What package is effected by this issue?

@web3-onboard/injected

### Is this a build or a runtime issue?

Build, Runtime

### Package Version

2.7.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@slotZero01 by default Web3-onboard will only show the injected wallets that a user has available (added as a browser extension and injected into the page).
Because Exodus and MetaMask inject to the same namespace (`window.ethereum`) Exodus will override the MetaMask provider and thus MetaMask will not be shown because it is not available on the browser even if it is added as an extension.
You can see this in the browser console by typing in `window.ethereum` and looking at the provider.
If you would like to show MetaMask even through it isnt available that is possible, please see docs here - https://onboard.blocknative.com/docs/wallets/injected#display-unavailable-wallets

**Comment by slotZero01** [comment]
@Adamj1232 ok, so only 1 wallet can be working in 1 namespace right? Then how do you decide which provider overwrites the others?

Is there any way from the exampe I gave to make metamask wallet to be prioritized?

**Comment by Adamj1232** [comment]
@slotZero01 we (web3-onboard) does not determine this. This is completely based on load time by the extension with the slowest load overriding the space.
There is now way to prioritize as we don't control the wallets available within the window. 
The only way to handle this is let the user know to disable other wallets to (if available) set a wallet to not be the primary wallet which usually scopes the wallet to a different namespace on the window.
