### ISSUE TITLE
WalletConnect V2 doesn't show all accounts connected

### ISSUE THREAD

**Issue by sirpy** [blocknative/web3-onboard#1678]
### Current Behavior

shows only one connected account

### Expected Behavior

show list of connected accounts

### Steps To Reproduce

1. start wc2 connection here https://reactdemo.blocknative.com/
2. connect to wallet https://react-web3wallet.vercel.app/walletconnect
3. choose multiple both accounts in https://react-web3wallet.vercel.app/walletconnect
4. back in https://reactdemo.blocknative.com/ only one account is shown

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

latest

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@sirpy after looking into this I believe this is expected behavior as this flow only approves the multiple accounts. There isnt ability built into the walletconnect demo wallet to switch accounts setting a primary account which would be what is expected within web3-onboard.
For example when you connect through MetaMask you approve both accounts connecting but you only connect one account at first and you have to switch the primary account within MetaMask(or insert wallet name as MM doesnt work with v2 yet) and not the dapp.
