### ISSUE TITLE
disableModals doesn't work with WalletConnect

### ISSUE THREAD

**Issue by sirtimid** [blocknative/web3-onboard#2000]
### Current Behavior

We are implementing a custom auto-connection feature but it doesn't work properly with WalletConnect because even if we set `disableModals` to `true`, it still shows the QR modal. 

### Expected Behavior

Since we set `disableModals` to `true` it should just try to connect with WalletConnect without showing the modal. 

### Steps To Reproduce

Call 

```js
await onboard.connectWallet({
  autoSelect: { label: 'WalletConnect', disableModals: true },
})
```

It shows the QR modal

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.21.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Anything else?

Perhaps the `showQrModal` parameter on `@web3-onboard/walletconnect` package should be based on `disableModals`.

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
Disable modals is only for Web3-Onboard modals. To disable to the wallet connect modal, which wouldn't make much sense as that connector is focused on connecting mobile wallets, you would have to set that within the WalletConnect module init `qrModalOptions.showQrModal`
Closing as this is the expected behavior for that variable within the onboard init and wallet connection flow.
