### ISSUE TITLE
[Feature]: calling onboard.connectWallet with the autoSelect option should not flash the modal

### ISSUE THREAD

**Issue by morozj01** [blocknative/web3-onboard#849]
### Feature Description

For background context I am following the example provided here: https://docs.blocknative.com/onboard/core#auto-selecting-a-wallet

Auto-selecting is working well, however when the page refreshes, or the user navigates to a different route - the modal flashes for a second, immediately displays a 'Connected' message, and then closes. 

Ideally the library would allow controlling this behavior so that page refresh and navigation could occur without the modal opening/closing - which would make the app feel a lot smoother from a UX perspective. 

I have attached a video depicting this behavior below. 

Thanks in advance and let me know if there's anything else I can provide! 

### Anything else?

Video of page refresh and navigation: 
https://user-images.githubusercontent.com/28926919/156272168-1a1eae32-6ebb-4025-88a0-d9ad2a174850.mp4

**Comment by aaronbarnardsound** [comment]
@morozj01 Thanks for the feedback and that makes sense. 

It is a little tricky as there are some edge cases in that maybe the user has revoked connection access to your app, so in that case you would probably still want the modal to indicate the connection request and then the confirmation of connection. We could just not show the connection confirmed modal when the wallet is auto selected (and there is a `disableConnectedModal` flag included in the connect wallet options), but in the case of having to re-establish connection between the wallet and the app, the flow is now inconsistent. Unfortunately there generally isn't a way of telling if the user has revoked connection access without asking for access and no reliable way of telling if the user is manually allowing access or if that promise resolved automatically since it is already granted. We could implement some sort of timeout to indicate that manual access needs to be granted, but that could be kind of brittle.

I'll experiment a little and see what we can come up with and i'll get back to you here.

**Comment by lobovkin** [comment]
> @morozj01 Thanks for the feedback and that makes sense.
> 
> It is a little tricky as there are some edge cases in that maybe the user has revoked connection access to your app, so in that case you would probably still want the modal to indicate the connection request and then the confirmation of connection. We could just not show the connection confirmed modal when the wallet is auto selected (and there is a `disableConnectedModal` flag included in the connect wallet options), but in the case of having to re-establish connection between the wallet and the app, the flow is now inconsistent. Unfortunately there generally isn't a way of telling if the user has revoked connection access without asking for access and no reliable way of telling if the user is manually allowing access or if that promise resolved automatically since it is already granted. We could implement some sort of timeout to indicate that manual access needs to be granted, but that could be kind of brittle.
> 
> I'll experiment a little and see what we can come up with and i'll get back to you here.

But there was no such behavior in the previous version. Also I can't find any mention "disableConnectedModal" in the repository.

**Comment by aaronbarnardsound** [comment]
Yes that is correct, this is unique to the new version.
The `disableConnectedModal` does not exist yet, i was suggesting something that we could add.

**Comment by morozj01** [comment]
@aaronbarnardsound Appreciate you taking a look at it - FWIW I think a flow where the connectWallet call results in an unresolved promise because it is waiting on some user action (without showing the modal) is acceptable - especially if there are essentially 2 flags -  `autoSelect`  and `disableConnectedModal` - controlling that behavior.

The application itself can be responsible for prompting the user to look at their wallet, implementing a timeout, or any other kind of use-case specific logic.

**Comment by jadbox** [comment]
Hey @aaronbarnardsound, `disableConnectedModal` option would be appreciated here too as we often need to auto reconnect the user's wallet on loading app pages after the user can already connected on a previous page (not a SPA).

**Comment by aaronbarnardsound** [comment]
@jadbox and @morozj01 thanks for the feedback. I am going to take a look at this tomorrow and might ping you all with a branch to test if that's ok.
