### ISSUE TITLE
[Bug]: Can’t choose MetaMask

### ISSUE THREAD

**Issue by bisio2332** [blocknative/web3-onboard#925]
### Current Behavior

Hello, I have a question about `Metamask`
In this documentation https://docs.blocknative.com/onboard, we can see the `Metamask` wallet http://joxi.ru/L21eVX3Iwg1Z42
But in the Live Demo https://reactdemo.blocknative.com/ `Metamask` is missing http://joxi.ru/v29eVX7I4zMWj2
How can I activate `Metamask` wallet?
Thank you

### Expected Behavior

Possibility of using `Metamask` to connecting 

### Onboard Version

2.1.1

### Node Version

16.13.2

**Comment by Adamj1232** [comment]
@bisio2332 do you have MM and CB wallet installed on your browser?
If that is the case, we released a new update to the injected-wallets package that allows both injected wallets to be shown/used
A note about injected wallets - If you do not see an injected wallet you are expecting to see you or your clients may need to disable other injected wallets that may be added to the browser. This is because many wallets inject into the window.ethereum namespace and will override each other. Some wallets such as Coinbase wallet do pass up the wallet providers injected before them but others do not. We are working with wallet providers to make this passing of previously injected providers upward a standard.

**Comment by bisio2332** [comment]
@Adamj1232 Thank you for your description now it’s much clear. I updated the library today, and now I can see `metamask`.  One more time thank you for your work 👍
